### ISSUE TITLE
最高亮度下息屏再亮屏會不顯示

### ISSUE THREAD

**Issue by Sean951106** [varieget/miui-force-DC#3]
最高亮度下息屏再亮屏會不顯示（變為黑屏）
手機功能皆正常 有震動、可接聽等等
盲操作將亮度調低即恢復正常

**Comment by varieget** [comment]
删除模块后重新安装，能否稳定复现？
机型是 munch 吗？当前 MIUI 版本？
可以肯定，V14.0.7.0.TLMCNXM 目前正常使用。

其他机型未经测试，基于 Android 14 的 MIUI 未经测试，HyperOS 未经测试。

提供一个思路，尝试 fastboot 刷入 V14.0.22.12.8.DEV 的 dtbo 分区，或者选择刷入第三方内核。

**Comment by Sean951106** [comment]
刪除後重裝還是一樣不行 最高亮度息屏再鎖屏一樣無法顯示螢幕（觸摸正常）
機型是k40 版本是eu的14.0.8.0

**Comment by varieget** [comment]
k40 和 k40s 有很大的不同，在 #2 把 k40s 的 displayfeature.default.so 加到了这个模块里，Changelog 写了 “仅在 Redmi K40S 上测试过，其他机型未经测试” 没写到 README 可能导致你误解了。这个模块是适用于 k40s 就是 munch 机型的。

你可以去酷安上找找 k40 的模块，那个机型比 k40s 更常见。
